### ISSUE TITLE
我只能访问twitter.com, 不知为何？

### ISSUE THREAD

**Issue by luckypoem** [Potatso/Manual#2]
HI.
见我的设置：http://i.imgur.com/xhofyMA.png ，我连接上后，访问显示ip的网站ip-adress.com,所显示的ip为我的代理服务器的ip.但是我只能访问twitter.com, 不知为何？

**Comment by neontorrent** [comment]
现在好像还是有这bug，要自己添加自定义规则，默认路由有时候就算你设的代理也没用。

**Comment by icodesign** [comment]
你用的不是我的 app
